name: Code style check
on:
  push:
    branches: [main]
  pull_request:

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip-lint-check]') == false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.15

      - name: Install deps
        run: bun install

      - name: Run prettier
        run: bun run lint
